spring:
  application:
    name: mall-store
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.96.20.181:3306/help_desk?serverTimezone=GMT%2B8&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000


mybatis-plus:
  #项目启动会检查xml配置存在(只在开发时候打开)
  #Project startup checks for the presence of xml configuration (only turned on during development)
  check-config-location: true
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    #whether to enable automatic camel case mapping, i.e. a similar mapping from the classical database column name A_COLUMN (underscore naming) to the classical Java property name aColumn (camel naming)
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #This configuration will print out the executed sql and can be used during development or testing with
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #表名下划线命名默认true
      #Default true for underscore naming of table names
      table-underline: true
      #id类型
      #ID type
      id-type: auto
