spring:
  application:
    name: mall-store
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.96.20.181:3306/help_desk?serverTimezone=GMT%2B8&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000


mybatis-plus:

  #Project startup checks for the presence of xml configuration (only turned on during development)
  check-config-location: true
  configuration:
    #whether to enable automatic camel case mapping, i.e. a similar mapping from the classical database column name A_COLUMN (underscore naming) to the classical Java property name aColumn (camel naming)
    map-underscore-to-camel-case: true
    #This configuration will print out the executed sql and can be used during development or testing with
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:

      #Default true for underscore naming of table names
      table-underline: true

      #ID type
      id-type: auto
